# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

############################## PRE ##############################

  before_all do
    ensure_git_status_clean
  end

#### Tests ####

desc "Run all Unit, UI"
lane :tests do
  run_tests(message: "Unit, UI")
end

desc "Run Unit tests"
lane :unit_tests do
  run_tests(message: "Unit", scheme: "Fastlane_ProjectTests")
end

desc "Run UI Tests"
lane :ui_tests do
  run_tests(message: "UI", scheme: "Fastlane_ProjectUITests")
end
	
desc "Check style and conventions"
lane :lint do
  oclint(strict: true)
end

####################### Build and Deploy #################################
	
desc "Build and prepare deployment"
lane :build_for_deploy do
  xcodebuild sdk: "iphoneos", configuration: "development"
end
	
end
